spring:
  profiles:
    active: ${PROFILES_ACTIVE}

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  sql:
    init:
      mode: ${DB_MODE}

  jpa:
    hibernate:
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        highlight_sql: true
        use_sql_comments: true

  servlet:
    multipart:
      max-request-size: ${MAX_REQUEST_SIZE}
      max-file-size: ${MAX_FILE_SIZE}

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            require: true
logging:
  config: classpath:logback/${PROFILES_ACTIVE}-logback.xml
  file:
    path: ${LOG_FILE_PATH}
    name: gabojait-rolling.log

springfox:
  documentation:
    swagger-ui:
      enabled: ${SWAGGER_ENABLED}
      base-url: ${SWAGGER_BASE_URL}

decorator:
  datasource:
    p6spy:
      enable-logging: ${P6SPY_ENABLED}

api:
  name: ${API_NAME}
  master:
    id: ${MASTER_ID}
  jwt:
    secret: ${JWT_SECRET}
    domain: ${JWT_DOMAIN}
    time:
      access: ${JWT_TIME_ACCESS}
      refresh: ${JWT_TIME_REFRESH}
  mail:
    address: ${MAIL_ADDRESS}

s3:
  access-key: ${S3_ACCESS_KEY}
  secret-key: ${S3_SECRET_KEY}
  bucket:
    profile-img: ${S3_PROFILE_IMG_BUCKET}
    portfolio-file: ${S3_PORTFOLIO_FILE_BUCKET}
  region: ${S3_REGION}

firebase:
  project:
    id: ${FIREBASE_PROJECT_ID}
  private:
    key-id: ${FIREBASE_PRIVATE_KEY_ID}
    key: ${FIREBASE_PRIVATE_KEY}
  client:
    email: ${FIREBASE_CLIENT_EMAIL}
    id: ${FIREBASE_CLIENT_ID}
    x509:
      cert:
        url: ${FIREBASE_CLIENT_CERT_URL}

sentry:
  dsn: ${SENTRY_DSN}
  traces-sample-rate: 1.0
  logging:
    minimum-event-level: info
    minimum-breadcrumb-level: info
