spring:
  profiles:
    default: local

###################
###### LOCAL ######
###################
---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gabojait_local?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 100
        show_sql: false
        format_sql: true
        highlight_sql: true
        use_sql_comments: true

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            require: true

  servlet:
    multipart:
      max-request-size: ${MAX_REQUEST_SIZE}
      max-file-size: ${MAX_FILE_SIZE}

logging:
  config: classpath:logback/develop-logback.xml
  file:
    name: gabojait-rolling.log

springfox:
  documentation:
    swagger-ui:
      base-url: ${SWAGGER_BASE_URL}

firebase:
  project:
    id: ${FIREBASE_PROJECT_ID}
  private:
    key-id: ${FIREBASE_PRIVATE_KEY_ID}
    key: ${FIREBASE_PRIVATE_KEY}
  client:
    email: ${FIREBASE_CLIENT_EMAIL}
    id: ${FIREBASE_CLIENT_ID}
    x509:
      cert:
        url: ${FIREBASE_CLIENT_CERT_URL}

sentry:
  dsn:
  traces-sample-rate: 1.0
  logging:
    minimum-event-level: info
    minimum-breadcrumb-level: info

s3:
  access-key: ${S3_ACCESS_KEY}
  secret-key: ${S3_SECRET_KEY}
  bucket:
    profile-img: ${S3_PROFILE_IMG_BUCKET}
    portfolio-file: ${S3_PORTFOLIO_FILE_BUCKET}
  region: ${S3_REGION}

api:
  name: "Gabojait Local"
  master:
    id: gabojait
  jwt:
    secret: ${JWT_SECRET}
    domain: ${JWT_DOMAIN}
    time:
      access: ${JWT_TIME_ACCESS}
      refresh: ${JWT_TIME_REFRESH}
  mail:
    address: ${MAIL_ADDRESS}

##################
###### TEST ######
##################
---
spring:
  config:
    activate:
      on-profile: test

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:~/gabojait
    username: sa
    password:

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 100
        show_sql: false
        format_sql: true
        highlight_sql: true
        use_sql_comments: true

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            require: true

  servlet:
    multipart:
      max-request-size: ${MAX_REQUEST_SIZE}
      max-file-size: ${MAX_FILE_SIZE}

logging:
  config: classpath:logback/develop-logback.xml
  file:
    name: gabojait-rolling.log

firebase:
  project:
    id: ${FIREBASE_PROJECT_ID}
  private:
    key-id: ${FIREBASE_PRIVATE_KEY_ID}
    key: ${FIREBASE_PRIVATE_KEY}
  client:
    email: ${FIREBASE_CLIENT_EMAIL}
    id: ${FIREBASE_CLIENT_ID}
    x509:
      cert:
        url: ${FIREBASE_CLIENT_CERT_URL}

sentry:
  dsn:
  traces-sample-rate: 1.0
  logging:
    minimum-event-level: info
    minimum-breadcrumb-level: info

s3:
  access-key: ${S3_ACCESS_KEY}
  secret-key: ${S3_SECRET_KEY}
  bucket:
    profile-img: ${S3_PROFILE_IMG_BUCKET}
    portfolio-file: ${S3_PORTFOLIO_FILE_BUCKET}
  region: ${S3_REGION}

api:
  name: "Gabojait Test"
  master:
    id: gabojait
  jwt:
    secret: ${JWT_SECRET}
    domain: ${JWT_DOMAIN}
    time:
      access: ${JWT_TIME_ACCESS}
      refresh: ${JWT_TIME_REFRESH}
  mail:
    address: ${MAIL_ADDRESS}

###################
###### ALPHA ######
###################
---
spring:
  config:
    activate:
      on-profile: alpha

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  sql:
    init:
      mode: ${SQL_INIT_MODE}

  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 100
        show_sql: false
        format_sql: true
        highlight_sql: true
        use_sql_comments: true

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            require: true

  servlet:
    multipart:
      max-request-size: ${MAX_REQUEST_SIZE}
      max-file-size: ${MAX_FILE_SIZE}

logging:
  config: classpath:logback/deploy-logback.xml
  file.name: gabojait-rolling.log

springfox:
  documentation:
    swagger-ui:
      base-url: ${SWAGGER_BASE_URL}

firebase:
  project:
    id: ${FIREBASE_PROJECT_ID}
  private:
    key-id: ${FIREBASE_PRIVATE_KEY_ID}
    key: ${FIREBASE_PRIVATE_KEY}
  client:
    email: ${FIREBASE_CLIENT_EMAIL}
    id: ${FIREBASE_CLIENT_ID}
    x509:
      cert:
        url: ${FIREBASE_CLIENT_CERT_URL}

sentry:
  dsn: ${SENTRY_DSN}
  environment: alpha
  traces-sample-rate: 1.0
  logging:
    minimum-event-level: info
    minimum-breadcrumb-level: info

s3:
  access-key: ${S3_ACCESS_KEY}
  secret-key: ${S3_SECRET_KEY}
  bucket:
    profile-img: ${S3_PROFILE_IMG_BUCKET}
    portfolio-file: ${S3_PORTFOLIO_FILE_BUCKET}
  region: ${S3_REGION}

api:
  name: "Gabojait Alpha"
  master:
    id: gabojait
  jwt:
    secret: ${JWT_SECRET}
    domain: ${JWT_DOMAIN}
    time:
      access: ${JWT_TIME_ACCESS}
      refresh: ${JWT_TIME_REFRESH}
  mail:
    address: ${MAIL_ADDRESS}

###################
##### RELEASE #####
###################
---
spring:
  config:
    activate:
      on-profile: release

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  sql:
    init:
      mode: ${SQL_INIT_MODE}

  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 100
        show_sql: false
        format_sql: true
        highlight_sql: true
        use_sql_comments: true

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            require: true

  servlet:
    multipart:
      max-request-size: ${MAX_REQUEST_SIZE}
      max-file-size: ${MAX_FILE_SIZE}

logging:
  config: classpath:logback/deploy-logback.xml
  file.name: gabojait-rolling.log

springfox:
  documentation:
    swagger-ui:
      base-url: ${SWAGGER_BASE_URL}

decorator:
  datasource:
    p6spy:
      enable-logging: ${P6SPY_ENABLED}

firebase:
  project:
    id: ${FIREBASE_PROJECT_ID}
  private:
    key-id: ${FIREBASE_PRIVATE_KEY_ID}
    key: ${FIREBASE_PRIVATE_KEY}
  client:
    email: ${FIREBASE_CLIENT_EMAIL}
    id: ${FIREBASE_CLIENT_ID}
    x509:
      cert:
        url: ${FIREBASE_CLIENT_CERT_URL}

s3:
  access-key: ${S3_ACCESS_KEY}
  secret-key: ${S3_SECRET_KEY}
  bucket:
    profile-img: ${S3_PROFILE_IMG_BUCKET}
    portfolio-file: ${S3_PORTFOLIO_FILE_BUCKET}
  region: ${S3_REGION}

sentry:
  dsn: ${SENTRY_DSN}
  environment: release
  traces-sample-rate: 1.0
  logging:
    minimum-event-level: info
    minimum-breadcrumb-level: info

api:
  name: ${API_NAME}
  master:
    id: gabojait
  jwt:
    secret: ${JWT_SECRET}
    domain: ${JWT_DOMAIN}
    time:
      access: ${JWT_TIME_ACCESS}
      refresh: ${JWT_TIME_REFRESH}
  mail:
    address: ${MAIL_ADDRESS}
