spring:
  profiles:
    active: ${PROFILES_ACTIVE}

  data:
    mongodb:
      host: ${DB_HOST}
      port: ${DB_PORT}
      database: ${DB_NAME}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      auto-index-creation: true
      authentication-database: admin

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE}
      max-request-size: ${MAX_REQUEST_SIZE}

springfox:
  documentation:
    swagger-ui:
      enabled: ${SWAGGER_ENABLED}

logging:
  config: classpath:logback/${PROFILES_ACTIVE}-logback.xml
  file:
    path: ${LOG_FILE_PATH}
    name: gabojait-rolling.log

api:
  name: ${PROFILES_ACTIVE}
  master:
    id: ${MASTER_ID}

  jwt:
    secret: ${JWT_SECRET}
    domain: ${JWT_DOMAIN}

s3:
  access-key: ${S3_ACCESS_KEY}
  secret-key: ${S3_SECRET_KEY}
  bucket:
    profile-img: ${S3_PROFILE_IMG_BUCKET}
    portfolio-file: ${S3_PORTFOLIO_FILE_BUCKET}
  region: ${S3_REGION}

firebase:
  project:
    id: ${FIREBASE_PROJECT_ID}
  private:
    key-id: ${FIREBASE_PRIVATE_KEY_ID}
    key: ${FIREBASE_PRIVATE_KEY}
  client:
    email: ${FIREBASE_CLIENT_EMAIL}
    id: ${FIREBASE_CLIENT_ID}
    x509:
      cert:
        url: ${FIREBASE_CLIENT_CERT_URL}
