name: Master - CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql
        env:
          MYSQL_DATABASE: ${{ secrets.DB_NAME }}
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Grant execute permission for Gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build
        env:
          API_NAME: ${{ secrets.API_NAME }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_MODE: ${{ secrets.DB_MODE }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          FIREBASE_CLIENT_CERT_URL: ${{ secrets.FIREBASE_CLIENT_CERT_URL }}
          FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL }}
          FIREBASE_CLIENT_ID: ${{ secrets.FIREBASE_CLIENT_ID }}
          FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
          FIREBASE_PRIVATE_KEY_ID: ${{ secrets.FIREBASE_PRIVATE_KEY_ID }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          JWT_DOMAIN: ${{ secrets.JWT_DOMAIN }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          JWT_TIME_ACCESS: ${{ secrets.JWT_TIME_ACCESS }}
          JWT_TIME_REFRESH: ${{ secrets.JWT_TIME_REFRESH }}
          LOG_FILE_PATH: ${{ secrets.LOG_FILE_PATH }}
          MAIL_ADDRESS: ${{ secrets.MAIL_ADDRESS }}
          MAIL_HOST: ${{ secrets.MAIL_HOST }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
          MAIL_PORT: ${{ secrets.MAIL_PORT }}
          MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
          MASTER_ID: ${{ secrets.MASTER_ID }}
          MAX_FILE_SIZE: ${{ secrets.MAX_FILE_SIZE }}
          MAX_REQUEST_SIZE: ${{ secrets.MAX_REQUEST_SIZE }}
          P6SPY_ENABLED: ${{ secrets.P6SPY_ENABLED }}
          PROFILES_ACTIVE: ${{ secrets.PROFILES_ACTIVE }}
          S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
          S3_PORTFOLIO_FILE_BUCKET: ${{ secrets.S3_PORTFOLIO_FILE_BUCKET }}
          S3_PROFILE_IMG_BUCKET: ${{ secrets.S3_PROFILE_IMG_BUCKET }}
          S3_REGION: ${{ secrets.S3_REGION }}
          S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          SWAGGER_BASE_URL: ${{ secrets.SWAGGER_BASE_URL }}
          SWAGGER_ENABLED: ${{ secrets.SWAGGER_ENABLED }}

      - name: Build and push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: gs97ahn/server
          tags: gabojait-release, gabojait-v1.0.0
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}